version: "3.9"

services:
  client:
    container_name: monta_no_mori-client
    build:
      dockerfile: ./Dockerfile
      context: ./client
    tty: true
    volumes:
      - ./client:/app
    ports:
      - 5173:5173

  server:
    container_name: monta_no_mori-server
    tty: true
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - ./server:/app
    environment:
      - DATABASE_URL=postgresql://root:secret@postgres:5432/monta_no_mori?sslmode=disable
    build:
      dockerfile: ./Dockerfile
      context: ./server

  postgres:
    image: postgres:14-alpine
    container_name: monta_no_mori-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=monta_no_mori

    volumes:
      - db-store:/var/lib/postgresql/data

volumes:
  db-store:
