// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreateImage(ctx context.Context, arg CreateImageParams) (Image, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteImage(ctx context.Context, id int64) error
	DeleteTag(ctx context.Context, id int64) error
	GetImage(ctx context.Context, id int64) (Image, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetTag(ctx context.Context, id int64) (Tag, error)
	GetTagByImageID(ctx context.Context, imageID sql.NullInt64) (Tag, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListImage(ctx context.Context, arg ListImageParams) ([]Image, error)
	ListTag(ctx context.Context, arg ListTagParams) ([]Tag, error)
	UpdateImage(ctx context.Context, arg UpdateImageParams) (Image, error)
	UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error)
}

var _ Querier = (*Queries)(nil)
