name: Deployment to Netlify and Fly.io

on:
  push:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install Dependencies
      run: cd client/ && npm ci

    - name: Build
      run: cd client/ && npm run build:prd

    - run: echo $VITE_BASE_API

    - name: Deploy to Netlify
      run: cd client/ && netlify deploy --dir=dist --prod
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Create credential file
        run: |
          echo '${{ secrets.CREDENTIAL_JSON }}' > server/credential.json

      - run: cd server/ && flyctl deploy --remote-only -a $APP_NAME
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_AUTH_TOKEN }}
          APP_NAME: monta-no-mori-server
